name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Maven settings.xml
      run: |
          mkdir -p ~/.m2
          echo '<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.GITHUB_ACTOR }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./sample2

    - name: Run Maven Tests
      working-directory: ./sample2
      run: mvn test

    - name: List files after build
      run: ls -R ./sample2/target

    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-java-app
        path: ./sample2/target/*.jar

    - name: Push JAR to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.run_number }}
        name: "Release ${{ github.run_number }}"
        files: ./sample2/target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      run: mvn deploy -X
      working-directory: ./sample2
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    # - name: Download Release Asset
    #   run: |
    #     mkdir -p lib
    #     curl -L -o file.zip https://github.com/shuti491/Dependencies/releases/download/30/dep1.jar
